### ISSUE TITLE
No need to close the plugin after Create

### ISSUE THREAD

**Issue by Andreslav** [codelastnight/to-path-figma#11]
Since there is no preview, it is difficult to predict what the result will be. Therefore, you have to reopen the plugin to adjust the settings.

**Comment by codelastnight** [comment]
you're totally right. I'll have them removed in the next update. I think eventually I would like the plugin to have live rendering/previews. Additionally, having the plugin remember the options after close might be helpful.

**Comment by codelastnight** [comment]
removed figma.close() in 1.2.0

**Comment by Andreslav** [comment]
On error (if you select multi-line text), the plugin still closes.

**Comment by Andreslav** [comment]
The plugin closes again, now it looks like an error.

**Comment by codelastnight** [comment]
hmm, I cant seem to replicate this error, what exactly are you doing to get the that error?

**Comment by Andreslav** [comment]
You are right now everything is working well.
