### ISSUE TITLE
Do not call scrollAndZoomIntoView()

### ISSUE THREAD

**Issue by Andreslav** [codelastnight/to-path-figma#12]
Nodes when starting a plugin are usually already in the viewing area. The call to scrollAndZoomIntoView () is inconvenient in the form of an unexpected shift (and offsets under the plugin, if it is in the center).

**Comment by codelastnight** [comment]
Got it, I'll have this also removed in the next update

**Comment by codelastnight** [comment]
fixed in 1.2
