### ISSUE TITLE
Negative offset does not work

### ISSUE THREAD

**Issue by Andreslav** [codelastnight/to-path-figma#15]
![2019-10-28_113059](https://user-images.githubusercontent.com/39444579/67663366-62c44d80-f976-11e9-9063-2a8a3258515f.png)

Departure is expected after all?

**Comment by codelastnight** [comment]
hmm... I'm not sure what I want the expected output of negative offset should be. should the plugin cut off and start from the letter of the offset? I'm not sure if theres a ton of cases where someone would want to do that , though. maybe I could remove negative values entirely from the offset.

**Comment by Andreslav** [comment]
> maybe I could remove negative values entirely from the offset.

I think it’s worth doing. Now it looks like a mistake.

**Comment by codelastnight** [comment]
removed negative offsets entirely in 1.3.0
