### ISSUE TITLE
Skewed results / misrotation 

### ISSUE THREAD

**Issue by dy** [codelastnight/to-path-figma#18]
![image](https://user-images.githubusercontent.com/300067/68774069-8c2ddc00-05fa-11ea-9639-a8bf4064e5f9.png)

Please note `TALKING` alignment. I suppose letters must be rotated by center origin.

**Comment by dy** [comment]
To illustrate:
![image](https://user-images.githubusercontent.com/300067/68774962-d19ed900-05fb-11ea-9d30-3422caa0587e.png)

**Comment by codelastnight** [comment]
Thanks for letting me know, this is an issue that i've been bothered by and I'm working on currently.

**Comment by codelastnight** [comment]
I've added a horizontal character spacing option in version 1.3.0, which should help in most cases 

but i still think things don't particularly look right, especially on wider text. The mathematical alignment is correct, but the optical alignment isn't (sometimes). I don't really know how I want to approach this yet. ( or if i even can)

**Comment by codelastnight** [comment]
closing for now, I think this works well enough

**Comment by dy** [comment]
[optical-properties](https://github.com/dy/optical-properties) to the rescue.
