### ISSUE TITLE
Add the ability to reverse the direction of the text

### ISSUE THREAD

**Issue by brendon** [codelastnight/to-path-figma#21]
I had a wave shape in the document that I wanted some text to follow so I duplicated the wave, then deleted the points that weren't necessary so that I just had a point-to-point curve. Unfortunately the nodes are in the incorrect order on the path so the text ends up backward:

![image](https://user-images.githubusercontent.com/81871/80926261-36d4c980-8dea-11ea-90c1-5e997aa28fbd.png)

I currently can't figure out a way to reverse the nodes so I'll probably have to redraw the line from scratch but that'll mean it's not exactly the same as the wave it's trying to follow :)

In Affinity I think there's a way to reverse the direction of the text in cases like these. I think that'd be a good option here :)

**Comment by codelastnight** [comment]
Oh true, this is a feature I haven't really thought about before... I'll if I can put something together in the next week or so

**Comment by brendon** [comment]
Thanks @codelastnight :) My assumption is that the fix would be fairly simple: Have a tick box option for reversing, then just reverse the nodes in the array before carrying on with the layout? :)

**Comment by codelastnight** [comment]
Hi, I finally updated the code (update 1.5.0)
Sorry for the delay, life & school got really stressful last quarter and I couldn't work on this at all...

**Comment by brendon** [comment]
Hi @codelastnight, don't worry about that! Personal life should always trump open source :D

I've just tried it out and it works great! Thank you so much for taking the time to implement this. I know it'll please a lot of people :D
